import type { TaskType } from "../state.js";

export function brainstormSystemPrompt(taskType: TaskType, taskDescription: string, taskDir: string): string {
  if (taskType === "debug") {
    return [
      "[PI-PI — DEBUG PHASE]",
      `Problem: ${taskDescription}`,
      "",
    "Read-only diagnosis mode.",
    "",
    "# FORBIDDEN — do NOT do any of these:",
    "- Do NOT modify project source code (no write or edit tools on project files)",
    "- Do NOT create or modify any files outside the task directory",
    "- Do NOT implement fixes — only diagnose and recommend",
    "",
    "# Your job:",
    "1. Clarify the problem with the user if needed",
    '2. Spawn explore subagents via Agent(subagent_type="Explore", ...) for codebase research',
    "3. Use bash to run commands, check logs, reproduce issues",
    "4. Use tools to trace the bug:",
    "   - cbm_search/cbm_search_code: find relevant code by concept or text",
    "   - lsp goToDefinition, findReferences, hover: precise navigation and type info",
    "   - lsp goToImplementation: check interface implementors",
    "   - lsp diagnostics: find type errors",
    "   - cbm_trace: trace call chains to/from suspect functions",
    "   - ast_search: find structural patterns (e.g. error handling, goroutines)",
      "",
      "IMPORTANT: Always specify subagent_type. Use Explore for codebase, Librarian for external docs.",
      "",
      "Produce two files:",
      `- ${taskDir}/USER_REQUEST.md — the fix request derived from your diagnosis`,
      `- ${taskDir}/RESEARCH.md — root cause analysis, evidence, recommended fix approach`,
      "",
      "RESEARCH.md structure:",
      "## Affected Code",
      "(file paths + what each does)",
      "## Architecture Context",
      "(how pieces connect, call chains, dependencies)",
      "## Constraints & Edge Cases",
      "## Open Questions",
      "(things that need user clarification)",
      "## Recommended Approach",
      "",
      "When both files are complete, call pp_phase_complete with a brief summary.",
    ].join("\n");
  }

  if (taskType === "brainstorm") {
    return [
      "[PI-PI — BRAINSTORM]",
      `Topic: ${taskDescription}`,
      "",
      "Open-ended conversation mode. Explore ideas, analyze tradeoffs, discuss approaches.",
      'Spawn subagents: Agent(subagent_type="Explore", ...) for codebase, Agent(subagent_type="Librarian", ...) for external docs.',
      "IMPORTANT: Always specify subagent_type. Do NOT omit it.",
      "Do NOT modify project source code.",
      "",
      "When you and the user reach conclusions or agree on an approach, write:",
      `- ${taskDir}/USER_REQUEST.md — what the user wants`,
      `- ${taskDir}/RESEARCH.md — findings, context, open questions`,
      "",
      "Then call pp_phase_complete with a brief summary.",
    ].join("\n");
  }

  return [
    "[PI-PI — BRAINSTORM PHASE]",
    `Task: ${taskDescription}`,
    "",
    "Your job is to produce USER_REQUEST.md and RESEARCH.md — complete enough that",
    "downstream agents can work without re-exploring the codebase or re-interviewing the user.",
    "",
    "# FORBIDDEN — do NOT do any of these:",
    "- Do NOT modify project source code (no write or edit tools on project files)",
    "- Do NOT create or modify any files outside the task directory",
    "- Do NOT start implementing — only research and document",
    "",
    "# Steps:",
    "1. Clarify requirements with the user if anything is ambiguous",
    '2. Spawn explore subagents via Agent(subagent_type="Explore", ...) for codebase research',
    '3. Spawn librarian subagents via Agent(subagent_type="Librarian", ...) for external docs/library research',
    "4. Use tools to understand code structure:",
    "   - cbm_search: natural-language search across all symbols",
    "   - cbm_search_code: graph-augmented grep (deduplicates into functions)",
    "   - lsp documentSymbol, goToDefinition, findReferences, goToImplementation, hover",
    "   - cbm_trace: trace call chains for dependency understanding",
    "   - ast_search: find structural patterns across the codebase",
    "5. Ask the user follow-up questions as needed",
    "6. Write findings into RESEARCH.md as results come back — don't wait for all subagents",
    "",
    "IMPORTANT: Always specify subagent_type. Use Explore for codebase, Librarian for external docs.",
    "",
    "Produce two files:",
    `- ${taskDir}/USER_REQUEST.md — clear statement of what needs to be done`,
    `- ${taskDir}/RESEARCH.md — codebase findings, architecture notes, constraints, open questions`,
    "",
    "RESEARCH.md structure:",
    "## Affected Code",
    "(file paths + what each does)",
    "## Architecture Context",
    "(how pieces connect, call chains, dependencies)",
    "## Constraints & Edge Cases",
    "## Open Questions",
    "(things that need user clarification)",
    "## Recommended Approach",
    "",
    "Do NOT modify any files except .md files in the task directory.",
    "When both files are produced and thorough, call pp_phase_complete with a brief summary.",
  ].join("\n");
}
