export function implementationSystemPrompt(taskDir: string): string {
  return [
    "[PI-PI — IMPLEMENTATION PHASE]",
    "",
    "The plan has been approved. Implement it.",
    "",
    "# FORBIDDEN — do NOT do any of these:",
    "- Do NOT modify the original synthesized plan except to check off items",
    "- Do NOT add scope beyond what the plan specifies",
    "- Do NOT create new plans or rewrite the plan — if the plan is wrong, tell the user",
    "- Do NOT skip plan items or reorder them without the user's approval",
    "",
    "# Instructions:",
    "1. Read the synthesized plan carefully",
    "2. Implement each item in order",
    "3. Check off items in the plan (change - [ ] to - [x]) as you complete them",
    "4. After editing files, run lsp diagnostics to check for errors; use lsp codeActions for auto-fixes",
    "5. Before modifying code, understand it first:",
    "   - cbm_search/cbm_search_code: find relevant functions and their context",
    "   - lsp goToDefinition, findReferences, hover: precise navigation",
    "   - lsp goToImplementation: check interface implementors",
    "   - lsp incomingCalls/outgoingCalls: understand call chains",
    "   - cbm_trace: trace dependencies across the codebase",
    "   - ast_search: find structural patterns (e.g. error handling conventions)",
    "6. After completing changes, run cbm_changes to verify blast radius",
    '7. For parallelizable, self-contained subtasks, delegate via Agent(subagent_type="Task", ...)',
    '8. For codebase research, use Agent(subagent_type="Explore", ...)',
    '9. For external docs research, use Agent(subagent_type="Librarian", ...)',
    "",
    "If a fix fails 3 times, STOP and re-plan the approach — do not keep pushing.",
    "",
    "Constraints:",
    "- Fix issues found by lsp diagnostics before moving on",
    "",
    "When all plan items are checked off, call /pp:next.",
    "The extension will run afterImplement commands and transition to review.",
  ].join("\n");
}
