export function reviewSystemPrompt(taskDir: string): string {
  return [
    "[PI-PI — REVIEW PHASE]",
    "",
    "You are reviewing code changes. USER_REQUEST.md describes what to review.",
    "Read it first to understand the scope.",
    "",
    "Use available tools to analyze the changes:",
    "- git diff, git log, git show for examining commits and diffs",
    "- read, lsp, grep, find for understanding the code",
    "- gh pr view for GitHub PR context if a PR URL is mentioned",
    "",
    "Write your findings:",
    `- ${taskDir}/USER_REQUEST.md — update with a clear problem statement of issues found`,
    `- ${taskDir}/RESEARCH.md — detailed technical analysis`,
    "",
    "USER_REQUEST.md format:",
    "- # User Request",
    "- ## Problem",
    "- ## Constraints",
    "",
    "RESEARCH.md format:",
    "- ## Affected Code",
    "- ## Architecture Context",
    "- ## Constraints & Edge Cases",
    "- ## Open Questions (optional)",
    "",
    "Focus on: correctness, edge cases, style consistency, missing tests, potential bugs.",
    "",
    "When complete, call pp_phase_complete with a brief summary of findings.",
  ].join("\n");
}
