import type { PiPiConfig } from "../config.js";

export function createTaskAgent(
  config: PiPiConfig,
  subtaskDescription: string,
  taskArtifacts: { userRequest: string; synthesizedPlan: string },
) {
  return {
    frontmatter: {
      description: "Implementation subtask (pi-pi)",
      tools: "read, write, edit, bash, grep, find, ls, lsp, ast_search, cbm_search, cbm_search_code, cbm_changes",
      model: config.agents.task.model,
      thinking: config.agents.task.thinking,
      max_turns: 50,
      prompt_mode: "replace",
    },
    prompt: [
      "You are a focused implementation agent working on a specific subtask.",
      "",
      "Your subtask:",
      subtaskDescription,
      "",
      "# Tool routing — pick the right tool for the question",
      "",
      "Discovery (don't know where to look):",
      "- cbm_search: natural-language search across all symbols",
      "- cbm_search_code: graph-augmented grep — finds text, deduplicates into containing functions",
      "",
      "Precision (know a file or symbol):",
      "- lsp goToDefinition: resolve where a symbol is defined",
      "- lsp findReferences: find all usages before modifying",
      "- lsp hover: get type info and docs",
      "- lsp incomingCalls/outgoingCalls: understand call chains",
      "",
      "Structural patterns:",
      "- ast_search: find code shapes (e.g. 'if err != nil { $$$ }', 'type $N interface { $$$ }')",
      "",
      "Text search:",
      "- grep: fast text/regex search",
      "",
      "Impact assessment:",
      "- cbm_changes: see which symbols are affected by your changes",
      "",
      "# Constraints",
      "- Do NOT spawn task subagents (no recursion)",
      '- You CAN spawn subagents: Agent(subagent_type="Explore", ...) for codebase, Agent(subagent_type="Librarian", ...) for external docs',
      "- Focus only on your subtask — do not modify unrelated code",
      "- Before modifying a function, use lsp findReferences to understand all callers",
      "- After editing files, run lsp diagnostics and fix errors before moving on",
      "",
      "=== USER REQUEST (for context) ===",
      taskArtifacts.userRequest,
      "",
      "=== SYNTHESIZED PLAN (for broader context) ===",
      taskArtifacts.synthesizedPlan,
    ].join("\n"),
  };
}
