export const ALL_CBM_TOOLS = "cbm_search, cbm_search_code, cbm_trace, cbm_changes, cbm_query, cbm_architecture";

export const TOOL_ROUTING = [
  "# Tool routing — pick the right tool for the question",
  "",
  "Discovery (don't know where to look):",
  "- cbm_search: natural-language search across all indexed symbols (query='deploy release')",
  "- cbm_search with semantic_query: vector similarity (e.g. ['deploy','install','upgrade'])",
  "- cbm_search_code: graph-augmented grep — deduplicates matches into containing functions",
  "- lsp workspaceSymbol: type-aware symbol search across workspace",
  "",
  "Precision (know a file or symbol):",
  "- lsp goToDefinition: jump to where a symbol is defined",
  "- lsp findReferences: find all usages of a symbol (zero false positives)",
  "- lsp hover: get type info and documentation",
  "- lsp goToImplementation: find all types implementing an interface",
  "- lsp documentSymbol: list all symbols in a file",
  "",
  "Call chains and dependencies:",
  "- lsp incomingCalls/outgoingCalls: who calls this / what does it call (accurate, needs file+line)",
  "- cbm_trace: same but by function name, works across the whole graph",
  "- cbm_query: Cypher graph queries for complex multi-hop patterns",
  "",
  "Structural patterns (code shapes):",
  "- ast_search: AST-aware matching (e.g. 'if err != nil { $$$ }', 'go $FUNC($$$)', 'type $N interface { $$$ }')",
  "",
  "Text search:",
  "- grep: fast ripgrep-based text/regex search",
  "",
  "Verification:",
  "- lsp diagnostics: type errors and lint issues on a file",
  "- lsp codeActions: auto-fix suggestions for diagnostics errors",
  "",
  "Impact and architecture:",
  "- cbm_changes: git diff → affected symbols + blast radius",
  "- cbm_architecture: high-level codebase structure overview",
].join("\n");
